name: generate_numbers
description: Game for guessing the generated number.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  presentation:
    path: packages/presentation

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 2.2.0
  injectable_generator: 1.5.4


flutter:

  uses-material-design: true